/**
 * LorvenLearn Course Seeder (REST API version)
 * Works with any Node.js version — no gRPC, no SDK, just HTTP.
 * Run: node scripts/seedREST.mjs
 */

import { readFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { createSign } from 'crypto';

const __dirname = dirname(fileURLToPath(import.meta.url));

// ── Load service account ──────────────────────────────────────────
const SA_PATH = resolve(__dirname, '../serviceAccountKey.json');
let sa;
try {
  sa = JSON.parse(readFileSync(SA_PATH, 'utf8'));
} catch {
  console.error('\n❌ serviceAccountKey.json not found in project root.\n');
  process.exit(1);
}

const PROJECT_ID = sa.project_id;
const DB_ID = 'ai-studio-371bd5a3-f7f5-47f8-b691-2c68455fa731';
const FIRESTORE_BASE = `https://firestore.googleapis.com/v1/projects/${PROJECT_ID}/databases/${DB_ID}/documents`;

// ── JWT helpers (to avoid any SDK) ────────────────────────────────
function base64url(input) {
  const buf = typeof input === 'string' ? Buffer.from(input, 'utf8') : input;
  return buf.toString('base64').replace(/=/g, '').replace(/\+/g, '-').replace(/\//g, '_');
}

async function getAccessToken() {
  const now = Math.floor(Date.now() / 1000);
  const header = base64url(JSON.stringify({ alg: 'RS256', typ: 'JWT' }));
  const claim = base64url(JSON.stringify({
    iss: sa.client_email,
    scope: 'https://www.googleapis.com/auth/datastore',
    aud: 'https://oauth2.googleapis.com/token',
    iat: now,
    exp: now + 3600,
  }));

  const sign = createSign('RSA-SHA256');
  sign.update(`${header}.${claim}`);
  const sig = base64url(sign.sign(sa.private_key));
  const jwt = `${header}.${claim}.${sig}`;

  const res = await fetch('https://oauth2.googleapis.com/token', {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: `grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Ajwt-bearer&assertion=${jwt}`,
  });
  const data = await res.json();
  if (!data.access_token) throw new Error(JSON.stringify(data));
  return data.access_token;
}

// ── Convert JS → Firestore REST format ────────────────────────────
function toFirestore(val) {
  if (val === null || val === undefined) return { nullValue: null };
  if (typeof val === 'boolean') return { booleanValue: val };
  if (typeof val === 'number') return Number.isInteger(val) ? { integerValue: String(val) } : { doubleValue: val };
  if (typeof val === 'string') return { stringValue: val };
  if (Array.isArray(val)) return { arrayValue: { values: val.map(toFirestore) } };
  if (typeof val === 'object') {
    const fields = {};
    for (const [k, v] of Object.entries(val)) fields[k] = toFirestore(v);
    return { mapValue: { fields } };
  }
  return { stringValue: String(val) };
}

function toDoc(obj) {
  const fields = {};
  for (const [k, v] of Object.entries(obj)) fields[k] = toFirestore(v);
  return { fields };
}

// ── Write one document via REST ────────────────────────────────────
async function writeDoc(token, collection, docId, data) {
  const url = `${FIRESTORE_BASE}/${collection}/${docId}`;
  const res = await fetch(url, {
    method: 'PATCH',
    headers: {
      'Authorization': `Bearer ${token}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(toDoc(data)),
  });
  if (!res.ok) {
    const err = await res.text();
    throw new Error(`HTTP ${res.status}: ${err}`);
  }
}

// ── 21 Rich Courses ───────────────────────────────────────────────
const COURSES = [
  { id: 'course_web-architecture', title: 'Advanced Web Architecture', description: 'Master planet-scale distributed systems, microservices, event-driven APIs with Kafka, CQRS, and zero-downtime Kubernetes deployments.', price: 1999, originalPrice: 4999, rating: 4.8, category: 'Web Development', level: 'Advanced', instructorName: 'Vikram Nair', isBestseller: true, thumbnailUrl: 'https://images.unsplash.com/photo-1593720213428-28a5b9e94613?w=600&auto=format&fit=crop', outcomes: ['Design microservices at scale','Implement event-driven APIs','Deploy to Kubernetes','Zero-downtime rollouts'], lessons: [{ id:'l1', title:'The Architecture Mindset', content:'C4 model, ADRs, system context — how senior engineers think before coding.', duration:22 },{ id:'l2', title:'Microservices vs Monorepos', content:'Real case studies from Netflix and Shopify. When to split and when to stay together.', duration:35 },{ id:'l3', title:'API Gateway Patterns', content:'BFF, aggregation gateways, rate limiting with Kong and AWS API Gateway.', duration:28 },{ id:'l4', title:'Event-Driven Systems with Kafka', content:'Topics, partitions, consumer groups, idempotent producers — hands-on labs.', duration:45 },{ id:'l5', title:'CQRS & Event Sourcing', content:'Implement an event store and rebuild application state from immutable events.', duration:40 },{ id:'l6', title:'Kubernetes Production Rollouts', content:'Blue/green and canary deployments, Helm charts, autoscaling on GKE and EKS.', duration:50 }] },
  { id: 'course_uiux-design', title: 'UI/UX Design Systems Masterclass', description: 'Go from zero to professional designer. Master Figma, auto-layout, component systems, cognitive psychology of UX, and WCAG accessibility.', price: 1499, originalPrice: 3499, rating: 4.7, category: 'UI/UX Design', level: 'Intermediate', instructorName: 'Ananya Krishnaswamy', isBestseller: true, thumbnailUrl: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600&auto=format&fit=crop', outcomes: ['Build a Figma design system','Master UX research','Create accessible interfaces','Prototype micro-interactions'], lessons: [{ id:'l1', title:'Design Thinking Framework', content:"Stanford d.school's 5-stage model applied to real product challenges.", duration:20 },{ id:'l2', title:'Figma Auto-Layout & Variables', content:'Build responsive components that adapt without manual resizing.', duration:36 },{ id:'l3', title:'Color Theory for Digital UI', content:'HSL palettes, contrast ratios, semantic color tokens.', duration:28 },{ id:'l4', title:'Typography Systems', content:'Typographic scales, fluid typography with clamp(), font pairing.', duration:24 },{ id:'l5', title:'Component Architecture', content:'Atomic Design — atoms → molecules → organisms → templates.', duration:38 },{ id:'l6', title:'User Research & Usability Testing', content:'5-second tests, card sorting, moderated sessions, affinity maps.', duration:44 }] },
  { id: 'course_fullstack-react', title: 'Full-Stack React & Node.js Bootcamp', description: 'The most comprehensive MERN stack curriculum. React 19, TypeScript, Node.js, Express, PostgreSQL, Redis, OAuth 2.0, and CI/CD. Build 5 production projects.', price: 2499, originalPrice: 5999, rating: 4.9, category: 'Web Development', level: 'Intermediate', instructorName: 'Rajan Mehta', isBestseller: true, thumbnailUrl: 'https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=600&auto=format&fit=crop', outcomes: ['Build full-stack apps with React 19','JWT + OAuth authentication','Deploy with Docker & GitHub Actions','TypeScript generics mastery'], lessons: [{ id:'l1', title:'React 19 New Features', content:'Concurrent rendering, Server Components, useFormStatus, useOptimistic.', duration:30 },{ id:'l2', title:'TypeScript for React Devs', content:'Generics, discriminated unions, mapped types, advanced component props.', duration:42 },{ id:'l3', title:'Node.js Performance', content:'V8 engine, event loop deep dive, worker threads, profiling with clinic.js.', duration:38 },{ id:'l4', title:'PostgreSQL & Prisma ORM', content:'Complex queries, indexes, transactions, migrations, solving N+1.', duration:46 },{ id:'l5', title:'Redis Caching Strategies', content:'Cache-aside, write-through, session storage, rate limiting, pub/sub.', duration:35 },{ id:'l6', title:'Docker & CI/CD with GitHub Actions', content:'Multi-stage builds, docker-compose, automated testing + deployment.', duration:48 }] },
  { id: 'course_data-science', title: 'Data Science with Python — Zero to Production', description: 'Pandas, NumPy, Scikit-Learn, XGBoost, and FastAPI. Build 3 end-to-end projects: churn prediction, image classifier, stock forecasting.', price: 2999, originalPrice: 6499, rating: 4.8, category: 'Data Science', level: 'Beginner', instructorName: 'Dr. Priya Chandran', thumbnailUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&auto=format&fit=crop', outcomes: ['Clean real-world data','Train and tune ML models','Deploy models with FastAPI','Interactive dashboards with Plotly'], lessons: [{ id:'l1', title:'Python & Jupyter Fundamentals', content:'Conda setup, Python structures for data science, reproducible notebooks.', duration:25 },{ id:'l2', title:'Pandas: The Data Engineering Layer', content:'DataFrames, groupby, merge/join, pivot tables, missing data, time series.', duration:48 },{ id:'l3', title:'Exploratory Data Analysis', content:'Distribution analysis, correlation matrices, outlier detection, Seaborn.', duration:40 },{ id:'l4', title:'Feature Engineering', content:'Encoding, scaling, polynomial features, SHAP values, target encoding.', duration:38 },{ id:'l5', title:'Scikit-Learn Training & Validation', content:'Cross-validation, GridSearchCV, ensemble methods, evaluation metrics.', duration:44 },{ id:'l6', title:'Deploy Your Model as an API', content:'Package with joblib, serve via FastAPI, containerize, deploy to Railway.', duration:36 }] },
  { id: 'course_cybersecurity', title: 'Cybersecurity & Ethical Hacking', description: 'Kali Linux, Metasploit, Burp Suite, Nmap — the full offensive security lifecycle from recon to reporting. Prepares for CEH and OSCP.', price: 1899, originalPrice: 4499, rating: 4.7, category: 'Cybersecurity', level: 'Beginner', instructorName: 'Arjun Reddy', thumbnailUrl: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=600&auto=format&fit=crop', outcomes: ['Network recon with Nmap','Exploit with Metasploit','Intercept traffic with Burp Suite','Write pentest reports'], lessons: [{ id:'l1', title:'Security Fundamentals & CIA Triad', content:'Threat modeling, attack surfaces, vulnerability vs risk vs threat.', duration:22 },{ id:'l2', title:'Networking for Hackers', content:'TCP/IP, Wireshark, ARP poisoning, DNS spoofing, firewalls and IDS.', duration:40 },{ id:'l3', title:'Reconnaissance & OSINT', content:'Passive OSINT with Shodan and Maltego. Active Nmap NSE scanning.', duration:35 },{ id:'l4', title:'Exploitation with Metasploit', content:'MSF console, exploits, meterpreter payloads, post-exploitation, pivoting.', duration:48 },{ id:'l5', title:'Web App Security (OWASP Top 10)', content:'SQL Injection, XSS, CSRF, SSRF — demonstrated on vulnerable apps.', duration:50 },{ id:'l6', title:'Writing Pentest Reports', content:'Executive summary, CVSS ratings, technical findings, remediation steps.', duration:28 }] },
  { id: 'course_ai-ml', title: 'AI & Machine Learning Professional Certification', description: 'Math, PyTorch, transformers built from scratch, CNNs, LLM fine-tuning with LoRA. The most rigorous AI program on the platform.', price: 3499, originalPrice: 7999, rating: 4.9, category: 'AI & Machine Learning', level: 'Advanced', instructorName: 'Dr. Shruti Rao', isBestseller: true, thumbnailUrl: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=600&auto=format&fit=crop', outcomes: ['Neural nets from scratch','Fine-tune LLMs with LoRA','Computer vision pipelines','Production ML deployment'], lessons: [{ id:'l1', title:'Mathematics for ML', content:'Vectors, eigenvalues, gradient descent derivation, probability distributions.', duration:55 },{ id:'l2', title:'Neural Networks from NumPy', content:'Forward pass, backpropagation, weight init, vanishing gradients.', duration:60 },{ id:'l3', title:'Deep Learning with PyTorch', content:'Autograd, nn.Module, DataLoaders, training loops, Lightning.', duration:48 },{ id:'l4', title:'Transformers & Attention', content:'Self-attention math, multi-head attention, building GPT-2 from scratch.', duration:65 },{ id:'l5', title:'Computer Vision CNNs', content:'Convolutions, pooling, ResNet skip connections, U-Net segmentation.', duration:52 },{ id:'l6', title:'LLM Fine-Tuning & Deployment', content:'LoRA/QLoRA, quantization, vLLM serving, monitoring in production.', duration:58 }] },
  { id: 'course_flutter', title: 'Mobile App Development with Flutter & Dart', description: 'Build stunning iOS + Android + Web apps from one Dart codebase. Riverpod state management, Reanimated-style animations, Firebase integration, App Store publishing.', price: 2299, originalPrice: 4999, rating: 4.8, category: 'Mobile Development', level: 'Intermediate', instructorName: 'Kiran Pillai', thumbnailUrl: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=600&auto=format&fit=crop', outcomes: ['iOS + Android from one codebase','Master Riverpod','Smooth animations','Publish to both stores'], lessons: [{ id:'l1', title:'Dart Language Mastery', content:'Null safety, async/await, streams, generics, Dart VM vs AOT.', duration:30 },{ id:'l2', title:'Flutter Widget Deep Dive', content:'Stateless vs Stateful, InheritedWidget, three trees (Widget, Element, Render).', duration:38 },{ id:'l3', title:'State Management with Riverpod', content:'Providers, AsyncNotifier, family modifiers, scoping, testing.', duration:42 },{ id:'l4', title:'Advanced Animations', content:'AnimationController, Tween, Hero animations, Lottie, physics springs.', duration:36 },{ id:'l5', title:'Firebase Integration', content:'Firestore real-time sync, Storage, Auth with social sign-in, FCM.', duration:44 },{ id:'l6', title:'App Store Publishing', content:'Code signing, build flavors, release builds, metadata, review guidelines.', duration:28 }] },
  { id: 'course_devops', title: 'DevOps & Cloud Engineering Masterclass', description: 'Linux, Docker, Kubernetes, Terraform, AWS/GCP, Prometheus/Grafana, GitLab CI/CD. Deploy a real microservices app to EKS end-to-end.', price: 2799, originalPrice: 5999, rating: 4.8, category: 'DevOps', level: 'Advanced', instructorName: 'Suresh Balakrishnan', thumbnailUrl: 'https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?w=600&auto=format&fit=crop', outcomes: ['Provision cloud with Terraform','Kubernetes orchestration','CI/CD with GitLab','Monitor with Grafana'], lessons: [{ id:'l1', title:'Linux Internals for DevOps', content:'Process management, systemd, networking, shell scripting, cron.', duration:38 },{ id:'l2', title:'Docker Deep Dive', content:'Union filesystems, multi-stage builds, layer caching, Compose.', duration:42 },{ id:'l3', title:'Kubernetes Architecture', content:'Control plane, Deployments, Services, Ingress, RBAC.', duration:55 },{ id:'l4', title:'Terraform IaC', content:'HCL, modules, state management, deploying VPCs + EKS on AWS.', duration:48 },{ id:'l5', title:'GitLab CI/CD Pipelines', content:'Stages, parallel jobs, DinD, environment promotion, ArgoCD GitOps.', duration:44 },{ id:'l6', title:'Observability Stack', content:'Prometheus metrics, Grafana dashboards, Jaeger distributed tracing.', duration:40 }] },
  { id: 'course_digital-marketing', title: 'Digital Marketing & Growth Hacking', description: 'SEO, Google Ads, Meta Ads, email sequences, CRO, product-led growth. The exact playbooks used to grow SaaS products from 0 to 1M users.', price: 1299, originalPrice: 2999, rating: 4.6, category: 'Marketing', level: 'Beginner', instructorName: 'Meera Iyer', thumbnailUrl: 'https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?w=600&auto=format&fit=crop', outcomes: ['Profitable Google & Meta ads','Rank page 1 with SEO','Email sequences that convert','Data-driven decisions with GA4'], lessons: [{ id:'l1', title:'Growth Mindset & Funnel Math', content:'AARRR, cohort analysis, LTV:CAC, ICE scoring for experiments.', duration:24 },{ id:'l2', title:'SEO: Technical & Content', content:'Core Web Vitals, schema, keyword clustering, topical authority, backlinks.', duration:45 },{ id:'l3', title:'Google Ads Mastery', content:'Search, Display, PMax. Match types, quality score, ROAS bidding.', duration:38 },{ id:'l4', title:'Meta Ads: Facebook & Instagram', content:'Audience research, lookalikes, creative testing, scaling winning sets.', duration:40 },{ id:'l5', title:'Email Marketing & Automation', content:'Welcome sequences, behavioral triggers, segmentation, A/B subject lines.', duration:32 },{ id:'l6', title:'Analytics & CRO', content:'GA4 events, funnel analysis, heatmaps with Hotjar, A/B testing.', duration:36 }] },
  { id: 'course_stock-trading', title: 'Stock Market & Options Trading Mastery', description: 'Technical analysis, options Greeks, iron condors, and professional risk management used by institutional traders. Includes paper trading sessions.', price: 2499, originalPrice: 4999, rating: 4.7, category: 'Finance', level: 'Intermediate', instructorName: 'Rahul Saxena', thumbnailUrl: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=600&auto=format&fit=crop', outcomes: ['Read candlestick patterns','RSI, MACD & Bollinger Bands','Trade options with defined risk','Build a complete trading plan'], lessons: [{ id:'l1', title:'Market Structure & Order Flow', content:"Market makers, bid/ask spread, dark pools — how markets actually work.", duration:28 },{ id:'l2', title:'Technical Analysis Foundations', content:'Support/resistance, trendlines, Dow Theory, chart patterns, volume.', duration:42 },{ id:'l3', title:'Momentum Indicators', content:'RSI divergence, MACD histogram, Stochastic — combining without overfitting.', duration:38 },{ id:'l4', title:'Options: Calls, Puts & Greeks', content:'Intrinsic vs time value, delta hedging, theta decay, IV rank.', duration:46 },{ id:'l5', title:'Advanced Options Strategies', content:'Iron condors, bull put spreads, calendars — selecting strikes strategically.', duration:44 },{ id:'l6', title:'Risk Management & Psychology', content:'Kelly Criterion position sizing, max drawdown rules, journaling, FOMO.', duration:32 }] },
  { id: 'course_blockchain', title: 'Blockchain & Web3 Development with Solidity', description: 'Cryptographic foundations, Solidity smart contracts, ERC standards, NFT marketplace with ethers.js + wagmi, and DeFi AMM protocols.', price: 3199, originalPrice: 6999, rating: 4.8, category: 'Web Development', level: 'Advanced', instructorName: 'Venkat Subramanian', thumbnailUrl: 'https://images.unsplash.com/photo-1644361566696-3d442b5b482a?w=600&auto=format&fit=crop', outcomes: ['Audit Solidity contracts','Build NFT marketplaces','DeFi AMM protocols','Deploy to Ethereum & Polygon'], lessons: [{ id:'l1', title:'Blockchain Cryptography', content:'SHA-256, Merkle trees, elliptic curve keys, digital signatures.', duration:35 },{ id:'l2', title:'Solidity Smart Contracts', content:'Types, mappings, modifiers, events, reentrancy and overflow attacks.', duration:50 },{ id:'l3', title:'ERC Standards: 20, 721, 1155', content:'Token interfaces, OpenZeppelin, metadata standards, EIP-2981 royalties.', duration:42 },{ id:'l4', title:'NFT Marketplace Development', content:'Listing, buying, auctioning NFTs. ETH transfers, MetaMask with wagmi.', duration:48 },{ id:'l5', title:'DeFi: AMM & Liquidity Pools', content:'Constant product formula (x*y=k), building Uniswap V2, impermanent loss.', duration:44 },{ id:'l6', title:'Smart Contract Security Auditing', content:'Slither, Echidna fuzzing, Certik audit report analysis.', duration:40 }] },
  { id: 'course_graphic-design', title: 'Graphic Design Masterclass — Adobe Suite', description: 'Photoshop photo manipulation, Illustrator vector art, InDesign print layouts, Premiere Pro social video. Build a 10-project job-ready portfolio.', price: 1599, originalPrice: 3499, rating: 4.7, category: 'UI/UX Design', level: 'Intermediate', instructorName: 'Kavitha Nair', thumbnailUrl: 'https://images.unsplash.com/photo-1558655146-d09347e92766?w=600&auto=format&fit=crop', outcomes: ['Retouch photos professionally','Vector logos in Illustrator','Print-ready brochures in InDesign','Social media video in Premiere'], lessons: [{ id:'l1', title:'Visual Design Principles', content:'Gestalt theory, hierarchy, contrast, alignment, proximity, white space.', duration:24 },{ id:'l2', title:'Photoshop: Retouching & Compositing', content:'Frequency separation, luminosity masks, Camera Raw color grading.', duration:48 },{ id:'l3', title:'Illustrator: Vector Mastery', content:'Pen tool, Pathfinder, mesh tool, 3D extrusion, logo systems.', duration:44 },{ id:'l4', title:'Brand Identity Design', content:'Logo process, brand guidelines, mockups, client decks.', duration:36 },{ id:'l5', title:'InDesign: Print & Editorial Layout', content:'Master pages, paragraph styles, GREP, print-ready PDFs with bleeds.', duration:32 },{ id:'l6', title:'Motion Graphics for Social Media', content:'After Effects keyframing, text animation, exporting for Reels and YouTube.', duration:38 }] },
  { id: 'course_personal-finance', title: 'Personal Finance & Wealth Building', description: 'Budgeting, debt elimination, tax optimization (India), index fund SIPs, real estate analysis, insurance. Practical India-specific personal finance.', price: 999, originalPrice: 1999, rating: 4.9, category: 'Finance', level: 'Beginner', instructorName: 'Anand Kumar', isBestseller: true, thumbnailUrl: 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=600&auto=format&fit=crop', outcomes: ['Zero-based budget that works','Invest in index funds via SIP','Optimize income tax in India','Build passive income'], lessons: [{ id:'l1', title:'6 Laws of Personal Finance', content:'Spend less, invest the difference, compound return math, mindset.', duration:20 },{ id:'l2', title:'Zero-Based Budgeting', content:'Tracking income/expenses, 50/30/20 vs zero-based, digital tools.', duration:28 },{ id:'l3', title:'Debt Strategy: Avalanche vs Snowball', content:'True cost of debt, credit card interest math, payoff calendar.', duration:24 },{ id:'l4', title:'Investing: Mutual Funds & ETFs', content:'Direct vs regular plans, Nifty 50 allocation, ELSS for tax saving.', duration:36 },{ id:'l5', title:'Indian Tax Planning (IT Act)', content:'Section 80C, HRA exemption, home loan deductions, new vs old regime.', duration:32 },{ id:'l6', title:'Building Passive Income', content:'Digital products, dividend investing, REITs, P2P lending.', duration:30 }] },
  { id: 'course_public-speaking', title: 'Public Speaking & Executive Presence', description: 'Dismantle stage fright for good. TED-style storytelling, vocal power, body language, and handling hostile Q&A with poise and authority.', price: 1099, originalPrice: 2499, rating: 4.9, category: 'Business', level: 'Beginner', instructorName: 'Sunita Agarwal', thumbnailUrl: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=600&auto=format&fit=crop', outcomes: ["Speak confidently to 1,000+","Hero's Journey storytelling","Vocal dynamics for authority","Handle Q&A with composure"], lessons: [{ id:'l1', title:'Neuroscience of Stage Fright', content:"Amygdala hijack and the reappraisal technique to convert fear to energy.", duration:18 },{ id:'l2', title:"Storytelling: Hero's Journey", content:'Joseph Campbell applied to business — opening hooks, conflict, CTA.', duration:28 },{ id:'l3', title:'Vocal Power & Articulation', content:'Diaphragmatic breathing, resonance, pace variation, eliminating filler words.', duration:32 },{ id:'l4', title:'Body Language & Stage Presence', content:'Power posing, eye contact patterns, purposeful movement, hands.', duration:26 },{ id:'l5', title:'Slide Design for Speakers', content:'Takahashi method, assertion-evidence, visualizing data for audiences.', duration:24 },{ id:'l6', title:'Handling Difficult Q&A', content:'PREP framework, bridging, hostile questioners, saying "I don\'t know".', duration:22 }] },
  { id: 'course_python-automation', title: 'Python Automation & Scripting Mastery', description: 'Automate everything — Playwright web scraping, Excel/PDF bots, Telegram bots, REST API integrations, and Celery task scheduling.', price: 1799, originalPrice: 3499, rating: 4.8, category: 'Web Development', level: 'Intermediate', instructorName: 'Ravi Kumar', thumbnailUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=600&auto=format&fit=crop', outcomes: ['Scrape with Playwright','Automate Excel with openpyxl','Build Telegram bots','Schedule tasks with Celery'], lessons: [{ id:'l1', title:'Automation Toolkit Overview', content:'Scraping, API integrations, file processing, GUI automation, bots.', duration:18 },{ id:'l2', title:'Web Scraping with Playwright', content:'Static and JS-rendered pages, pagination, anti-scraping bypass.', duration:44 },{ id:'l3', title:'Excel & PDF Automation', content:'openpyxl for Excel, ReportLab for PDFs, merging/splitting PDFs.', duration:36 },{ id:'l4', title:'API Automation & Integration', content:'httpx, OAuth token management, webhooks, service integration workflows.', duration:38 },{ id:'l5', title:'Bots: Telegram, Discord & Email', content:'python-telegram-bot, Discord.py slash commands, smtplib automation.', duration:40 },{ id:'l6', title:'Task Scheduling with Celery', content:'Celery + Redis, periodic tasks, monitoring with Flower, retries.', duration:34 }] },
  { id: 'course_photography', title: 'Professional Photography — Auto to Artistry', description: 'Exposure triangle, lighting from natural to studio strobes, portrait and landscape photography, Lightroom workflow, and building a paid client base.', price: 1599, originalPrice: 3299, rating: 4.7, category: 'Photography', level: 'All Levels', instructorName: 'Deepa Menon', thumbnailUrl: 'https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?w=600&auto=format&fit=crop', outcomes: ['Master manual camera controls','Portrait lighting setups','Lightroom editing workflow','Price and sell photography'], lessons: [{ id:'l1', title:'The Exposure Triangle', content:'Aperture, shutter speed, ISO — creative use of depth of field and motion blur.', duration:25 },{ id:'l2', title:'Composition Techniques', content:'Rule of thirds, leading lines, negative space, framing — breaking rules intentionally.', duration:28 },{ id:'l3', title:'Lighting: Natural to Studio', content:'Golden hour, overcast diffusion, Rembrandt lighting, budget strobe setups.', duration:40 },{ id:'l4', title:'Portrait Photography', content:'Directing subjects, focal lengths, catch lights, natural skin retouching.', duration:36 },{ id:'l5', title:'Adobe Lightroom Workflow', content:'Culling, HSL color grading, masking, export presets, batch editing.', duration:38 },{ id:'l6', title:'Building a Photography Business', content:'Pricing, client questionnaires, contracts, galleries, Instagram marketing.', duration:30 }] },
  { id: 'course_yoga', title: 'Yoga, Breathwork & Performance Optimization', description: 'Science-backed Hatha, Vinyasa, Yin yoga combined with Wim Hof breathwork, HRV monitoring, cold exposure, and sleep optimization protocols.', price: 899, originalPrice: 1799, rating: 4.8, category: 'Health', level: 'Beginner', instructorName: 'Meena Patel', thumbnailUrl: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=600&auto=format&fit=crop', outcomes: ['Daily yoga practice that sticks','Reduce cortisol with breathwork','Improve HRV and sleep','Cold exposure for recovery'], lessons: [{ id:'l1', title:'Science of Stress & Recovery', content:'HPA axis, cortisol cycles, HRV as a biomarker, parasympathetic activation.', duration:20 },{ id:'l2', title:'Hatha Yoga Foundations', content:'Sun salutation anatomy, alignment in standing poses, props for beginners.', duration:35 },{ id:'l3', title:'Breathwork: Pranayama & Wim Hof', content:'Nadi Shodhana, Kapalabhati, Wim Hof Method — evidence and safe protocols.', duration:30 },{ id:'l4', title:'Vinyasa Flow for Strength', content:'Core stability, functional strength, building your own 45-min flow.', duration:42 },{ id:'l5', title:'Yin Yoga & Fascia Release', content:'Long-hold poses for connective tissue, meridian theory, recovery weeks.', duration:36 },{ id:'l6', title:'Sleep Optimization Protocol', content:'Circadian rhythm, chronotypes, light timing, yoga nidra, supplements.', duration:28 }] },
  { id: 'course_prompt-engineering', title: 'AI Prompt Engineering & LLM Applications', description: 'Chain-of-thought, RAG architectures, LLM agents, fine-tuning, and running models locally with Ollama. Build AI-powered apps with Gemini, GPT-4, and Claude.', price: 1299, originalPrice: 2499, rating: 4.9, category: 'AI & Machine Learning', level: 'Beginner', instructorName: 'Geeta Sharma', isBestseller: true, thumbnailUrl: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=600&auto=format&fit=crop', outcomes: ['Consistent prompting techniques','RAG with vector databases','LLM agents with tool use','Fine-tune on your own data'], lessons: [{ id:'l1', title:'How LLMs Actually Work', content:'Tokenization, attention, context windows, temperature vs top-p.', duration:22 },{ id:'l2', title:'Prompt Engineering Techniques', content:'Zero-shot, few-shot, chain-of-thought, self-consistency, JSON mode.', duration:36 },{ id:'l3', title:'Building RAG Systems', content:'Chunking, embeddings, Pinecone/Chroma, retrieval strategies, hybrid search.', duration:44 },{ id:'l4', title:'LLM Agents & Tool Use', content:'ReAct framework, function calling, web browsing agents, memory management.', duration:40 },{ id:'l5', title:'Local LLMs with Ollama', content:'Llama 3, Mistral, quantization tradeoffs, GPU vs CPU, local Q&A chatbot.', duration:35 },{ id:'l6', title:'LLM Application Architecture', content:'Streaming, error handling, cost optimization, caching, evaluation, safety.', duration:38 }] },
  { id: 'course_guitar', title: 'Modern Guitar Mastery — Rock, Blues & Jazz', description: 'From open chords to sweep picking. Pentatonic scales, legato, modes, chord extensions, and recording professional-sounding demos at home.', price: 1299, originalPrice: 2499, rating: 4.8, category: 'Music', level: 'All Levels', instructorName: 'Rohan Sharma', thumbnailUrl: 'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=600&auto=format&fit=crop', outcomes: ['Pentatonic and modal scales','Blues with authentic feel','Improvise over jazz changes','Record professional home demos'], lessons: [{ id:'l1', title:'Guitar Anatomy & Posture', content:'Parts, hand posture, string names, building calluses efficiently.', duration:18 },{ id:'l2', title:'Open Chords & Rhythm', content:'Major/minor chords, strumming patterns, transitions, first 3 songs.', duration:30 },{ id:'l3', title:'Pentatonic Blues Mastery', content:'5 scale positions, blues box, bending, vibrato, 12-bar solo.', duration:40 },{ id:'l4', title:'Music Theory for Guitar', content:'CAGED system, major scale, modes (Dorian, Mixolydian), chord-scales.', duration:45 },{ id:'l5', title:'Advanced Techniques', content:'Legato, tapping, sweep picking arpeggios, hybrid picking, speed building.', duration:48 },{ id:'l6', title:'Home Recording & Tone', content:'Guitar→interface→DAW, Neural DSP amp sims, mixing DI guitars.', duration:36 }] },
  { id: 'course_kubernetes', title: 'Kubernetes & Cloud Native Engineering', description: 'Multi-tenant cluster architecture, Istio service mesh, GitOps with FluxCD, SLOs/error budgets, and chaos engineering. Real-world production K8s.', price: 2799, originalPrice: 5999, rating: 4.8, category: 'DevOps', level: 'Advanced', instructorName: 'Sathya Prakash', thumbnailUrl: 'https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?w=600&auto=format&fit=crop', outcomes: ['Multi-tenant K8s clusters','Istio service mesh','GitOps with FluxCD','SLOs and error budgets'], lessons: [{ id:'l1', title:'Kubernetes Resource Model', content:'Reconciliation loops, resource versioning, admission webhooks, custom controllers.', duration:45 },{ id:'l2', title:'Multi-Tenancy & RBAC', content:'Namespace isolation, ResourceQuotas, LimitRanges, OPA Gatekeeper.', duration:40 },{ id:'l3', title:'Networking: CNI, Ingress & Policies', content:'Calico vs Cilium, eBPF, NGINX/Envoy, cert-manager, zero-trust policies.', duration:48 },{ id:'l4', title:'Service Mesh with Istio', content:'mTLS, traffic management, canary routing, Kiali, ambient mode.', duration:44 },{ id:'l5', title:'GitOps with FluxCD', content:'Image auto-update, Kustomize overlays, fleet management, SOPS secrets.', duration:38 },{ id:'l6', title:'SRE: SLOs, SLAs & Incidents', content:'Error budget burn rates, on-call runbooks, blameless postmortems, chaos.', duration:42 }] },
];

// ── Main ──────────────────────────────────────────────────────────
async function main() {
  console.log(`\n🚀 LorvenLearn Course Seeder (REST mode)\n   Authenticating with Firebase...\n`);
  const token = await getAccessToken();
  console.log('   ✅ Authenticated\n');

  let success = 0;
  for (const course of COURSES) {
    const { id, ...data } = course;
    try {
      await writeDoc(token, 'courses', id, {
        ...data,
        instructorId: 'admin-seed',
        totalStudents: Math.floor(Math.random() * 4000) + 500,
        language: 'English',
        createdAt: new Date().toISOString(),
      });
      console.log(`   ✅ ${course.title}`);
      success++;
    } catch (err) {
      console.error(`   ❌ FAILED: ${course.title} — ${err.message}`);
    }
  }

  console.log(`\n🎉 Done! ${success}/${COURSES.length} courses written to Firestore.\n`);
}

main().catch(err => {
  console.error('❌ Fatal error:', err.message);
  process.exit(1);
});
